### ISSUE TITLE
ability to change number of image in one row

### ISSUE THREAD

**Issue by syrakozz** [fmitech/FMMosaicLayout#1]
can you plz add the abilty to change the number of image in one row, 
perexample i notice that always the number 1 row in contain 5 image,
no mare what
can you plz make the row more flexbile,

**Comment by JVillella** [comment]
Hey there @syrakozz,
Not sure if I follow entirely. You said the number of images in a row - that can be changed in the delegate method:

```
- (NSInteger)collectionView:(UICollectionView *)collectionView layout:(FMMosaicLayout *)collectionViewLayout numberOfColumnsInSection:(NSInteger)section {
    return 4; // Or whichever number you'd like
}
```

Does that help?

**Comment by syrakozz** [comment]
yes, tx
