### ISSUE TITLE
Can't get the Example Project to work

### ISSUE THREAD

**Issue by WilliamHua** [fmitech/FMMosaicLayout#10]
Using XCode 6.3.1, Cocoapods is 0.37.2

I opened the "Example" project in XCode and hit the run button and it gives these errors:

```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

I tried going to the directory to install the files from pod. I tried pod install and this is what I got:

```
[!] Unable to satisfy the following requirements:

- `FMMosaicLayout (from `../`)` required by `Podfile`
- `FMMosaicLayout (from `../`)` required by `Podfile`
- `FMMosaicLayout (= 0.1.1)` required by `Podfile.lock`
```

I downloaded it through ZIP and did not change any of the files.

**Comment by KyleGoddard** [comment]
Apologies William. Update the Podfile to the following and you should be able to install the pods and build the project.

```
source 'https://github.com/CocoaPods/Specs.git'

target 'FMMosaicLayout', :exclusive => true do
  pod "FMMosaicLayout"
end

target 'Tests', :exclusive => true do
  pod "FMMosaicLayout"
end
```

We'll look into why this is happening shortly.

**Comment by WilliamHua** [comment]
Thanks for the quick response, the solution worked perfectly.

**Comment by JVillella** [comment]
@WilliamHua Hey Will, if you look at the error again you will notice it is looking for 0.1.1. If you open the `Podfile.lock` in the example folder you'll see the following:

```
PODS:
  - FMMosaicLayout (0.1.1)

DEPENDENCIES:
  - FMMosaicLayout (from `../`)

EXTERNAL SOURCES:
  FMMosaicLayout:
    :path: ../

SPEC CHECKSUMS:
  FMMosaicLayout: 54c5e40fa93cdfc1f245bea9d59ce6faa27fbfea

COCOAPODS: 0.36.0.rc.1
```

Notice `FMMosaicLayout (0.1.1)`. Running pod install syncs with **existing** the `Podfile.lock`. You need to run `pod update` first. This will update your `Podfile.lock` to the most recent version of 0.1.4. Removing the `:path => "../"` expressions will prevent cocoapods from reading the local source files - and thus you won't be able to make any changes to the pod.

Happy coding!
Julian
