### ISSUE TITLE
More options for cell size?

### ISSUE THREAD

**Issue by pieterclaerhout** [fmitech/FMMosaicLayout#18]
Hi there,

I was looking into this library, and one thing I saw is that it currently only seems to support two cell sizes.

Is there any chance this can be changed to allow the app to specify the size of a cell in number of columns and rows? That would make the system much more flexible and customizable.

Kind regards,

pieter

**Comment by KyleGoddard** [comment]
Hi pieterclaerhout,

The number of cells is configurable via the delegate. Numbers can be changed by implementing `collectionView:layout:numberOfColumnsInSection:` in the `FMMosiacLayoutDelegate.` Higher column counts mean smaller cell width.

**Comment by pieterclaerhout** [comment]
Hi Kyle,

that's correct, but I was more looking for an option to specify a colspan and rowspan for a cell.

Kind regards,

pieter

**Comment by KyleGoddard** [comment]
Ah i see, that would be contrary to the algorithm used to calculate the cells automatically. The cell widths are calculated as part of the layout and are dictated base on the width of the available space and the number of columns.
