### ISSUE TITLE
setting numberOfColumnsInSection to odd number

### ISSUE THREAD

**Issue by mayooresan** [fmitech/FMMosaicLayout#19]
Currently when we set the `numberOfColumnsInSection` the result view will have double the amount of columns we requested.

E.g. we set the value to 2 then there is 4 columns in the collectionview.

Due to this, we can't add odd number columns (e.g. 3,5,7 etc.)

Could you please address this issue.

**Comment by KyleGoddard** [comment]
@mayooresan this is a limitation of the library, the algorithm used to calculate column numbers can only produce even numbers of columns.

**Comment by mayooresan** [comment]
Thanks for the reply.
