### ISSUE TITLE
How to Add Header and Footer View?

### ISSUE THREAD

**Issue by ToanNguyens** [fmitech/FMMosaicLayout#3]
Please show me how to add header and footer view in to your collection layout? 
I try but cannot by this:
- (UICollectionReusableView *)collectionView:(UICollectionView *)collectionView viewForSupplementaryElementOfKind:(NSString *)kind atIndexPath:(NSIndexPath *)indexPath;

**Comment by JVillella** [comment]
Hey @ToanNguyens. Header and footer views are not supported at the moment. I expect to add this in the coming future.

**Comment by JVillella** [comment]
Support has been added for this in the latest release `0.1.4`.
