### ISSUE TITLE
Release 0.1.2 breaks UI in landscape mode

### ISSUE THREAD

**Issue by fahad-mansoor-confiz** [fmitech/FMMosaicLayout#5]
Release 0.1.2 breaks UI in landscape mode, everything was working correctly before this release. I updated my pods and boom UI wrecked.

**Comment by JVillella** [comment]
Hey there, I've fixed this issue and pushed the pod to trunk. Thanks for letting us know!

**Comment by fahad-mansoor-confiz** [comment]
no problem.
Thanks for quick fix. :) :+1:
