### ISSUE TITLE
SWIFT. 

### ISSUE THREAD

**Issue by Mwiti** [fmitech/FMMosaicLayout#9]
Not an issue really but if you could issue this (see what i did there?) in swift, you would unlock the nth universe. Really. Like, seriously. All that aside, its a great control!

**Comment by JVillella** [comment]
A friend of mine @KyleGoddard rewrote this component in Swift. He did it just for you. Take a look! [KGFloatingDrawer](https://github.com/KyleGoddard/KGFloatingDrawer).

**Comment by JVillella** [comment]
Are you looking for an example of how to use it in Swift? or a rewrite in Swift?

**Comment by Mwiti** [comment]
Sorry i missed your reply... I wanted to know how i could implement this in swift. An example would be perfect. I'm not versed in Objective C as much so it was hard to use your control.

**Comment by aqeelb** [comment]
@Mwiti Install via CocoaPods. Use bridging header to import the file. Finally, import the module into the ViewController.swift

**Comment by aqeelb** [comment]
Install via CocoaPods. Use bridging header to import theFMMosaicLayout header file. Finally, import the module into the ViewController.swift

**Comment by desmochai** [comment]
@Mwiti Install via CocoaPods. Use bridging header to import theFMMosaicLayout header file. Finally, import the module into the ViewController.swift
